/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PantallasDevolucion;

import Controlador.interfaz.ICoordinadorDevolucion;
import dtos.ReservacionDTO;
import java.awt.Image;
import java.net.URL;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class PantallaEventoCancelar extends JFrame {
    
    private ICoordinadorDevolucion coordinadorDev;
    private ReservacionDTO reservacion;

    /**
     * Creates new form PantallaEventoCancelar
     */
    public PantallaEventoCancelar(ReservacionDTO reservacion, ICoordinadorDevolucion coordinadorDev) {
        this.reservacion = reservacion;
        this.coordinadorDev = coordinadorDev;
        initComponents();
        mostrarInformacionEvento();
        validarTiempo();
    }
    
    private void validarTiempo(){
        if(coordinadorDev.validarTiempo(reservacion.getBoleto().getEvento())){
            JOptionPane.showMessageDialog(this, "El evento está a menos de 48 horas de ocurrir, por lo que no puede ser cancelado.");
            coordinadorDev.abrirConsultar(reservacion.getUsuario());
            dispose();
        }
    }
    
    public void setReservacion(ReservacionDTO reservacion){
        limpiar();
        this.reservacion = reservacion;
        mostrarInformacionEvento();
    }
    
    private void mostrarInformacionEvento(){
        txtTitulo.setText(reservacion.getBoleto().getEvento().getNombreEvento());
        txtInfo.setText(reservacion.getBoleto().getEvento().getInformacionEvento());
        DateTimeFormatter formateadorFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter formateadorHora = DateTimeFormatter.ofPattern("HH:mm");
        txtFechaHora.setText(String.valueOf(reservacion.getBoleto().getEvento().getFechaHora().format(formateadorFecha)) + " - " + String.valueOf(reservacion.getBoleto().getEvento().getFechaHora().format(formateadorHora)));
        txtUbicacion.setText(reservacion.getBoleto().getEvento().getUbicacion().getNombre());
        
        // desplegar la imagen del evento
        String rutaLimpia = reservacion.getBoleto().getEvento().getUrlImagen().replace("/src/main/resources", "");
        String rutaAlternativa = reservacion.getBoleto().getEvento().getUrlImagen().replace("src/main/resources", "");

        URL imgUrl = getClass().getResource(rutaLimpia);
        if (imgUrl == null) {
            imgUrl = getClass().getResource(rutaAlternativa);
        }

        if (imgUrl != null) {
            ImageIcon icono = new ImageIcon(imgUrl);

            int ancho = 373;
            int alto = 234;

            Image imagenEscalada = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            iconEvento.setIcon(new ImageIcon(imagenEscalada));
        }
        iconEvento.setText("");
    }

    public void limpiar(){
        txtTitulo.setText("");
        txtInfo.setText("");
        txtFechaHora.setText("");
        txtUbicacion.setText("");
        iconEvento.setIcon(null);
        iconEvento.setText("");
        reservacion = null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        pnlAzul = new javax.swing.JPanel();
        lblPotroEventos = new javax.swing.JLabel();
        pnlAzulFuerte = new javax.swing.JPanel();
        btnInicio = new javax.swing.JLabel();
        lblResumen = new javax.swing.JLabel();
        iconEvento = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextPane();
        txtFechaHora = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        pnl.setBackground(new java.awt.Color(255, 255, 255));

        pnlAzul.setBackground(new java.awt.Color(31, 92, 204));

        lblPotroEventos.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblPotroEventos.setForeground(new java.awt.Color(255, 255, 255));
        lblPotroEventos.setText("PotroEventos");

        javax.swing.GroupLayout pnlAzulLayout = new javax.swing.GroupLayout(pnlAzul);
        pnlAzul.setLayout(pnlAzulLayout);
        pnlAzulLayout.setHorizontalGroup(
            pnlAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAzulLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPotroEventos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAzulLayout.setVerticalGroup(
            pnlAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAzulLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblPotroEventos)
                .addContainerGap())
        );

        pnlAzulFuerte.setBackground(new java.awt.Color(0, 49, 141));

        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnInicioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout pnlAzulFuerteLayout = new javax.swing.GroupLayout(pnlAzulFuerte);
        pnlAzulFuerte.setLayout(pnlAzulFuerteLayout);
        pnlAzulFuerteLayout.setHorizontalGroup(
            pnlAzulFuerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAzulFuerteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAzulFuerteLayout.setVerticalGroup(
            pnlAzulFuerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAzulFuerteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblResumen.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblResumen.setText("Resumen Evento");

        iconEvento.setText("iconEvento");

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtTitulo.setText("Titulo Evento");

        txtInfo.setBorder(null);
        txtInfo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtInfo.setText("info evento");
        txtInfo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtInfo);

        txtFechaHora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtFechaHora.setText("Fecha : Hora");

        txtUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUbicacion.setText("Ubicacion");

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar ");
        btnCancelar.setBorder(null);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnRegresar.setBackground(new java.awt.Color(47, 47, 47));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAzulFuerte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iconEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addComponent(pnlAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlAzulFuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResumen)
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(txtTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtFechaHora)))
                .addGap(5, 5, 5)
                .addComponent(txtUbicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        coordinadorDev.abrirConsultar(reservacion.getUsuario());
        limpiar();
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        coordinadorDev.mostrarDevolucion(reservacion);
        limpiar();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnInicioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnInicioAncestorAdded
        // TODO add your handling code here:
        coordinadorDev.inicioAplicacion();
        limpiar();
        dispose();
    }//GEN-LAST:event_btnInicioAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnInicio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel iconEvento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPotroEventos;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnlAzul;
    private javax.swing.JPanel pnlAzulFuerte;
    private javax.swing.JLabel txtFechaHora;
    private javax.swing.JTextPane txtInfo;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
