/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Controlador.interfaz.ICoordinadorAplicacion;
import javax.swing.JPanel;

/**
 *
 * @author Aaron Burciaga - 262788
 * @author Brian Sandoval - 262741
 * @author Dayanara Peralta - 262695
 * @author María Valdez - 262775
 */
public class FrmPlantillaSistema extends javax.swing.JFrame {

    private ICoordinadorAplicacion coordinador;

    /**
     * Creates new form FrmPlantillaSistema
     */
    public FrmPlantillaSistema(ICoordinadorAplicacion coordinador) {
        this.coordinador = coordinador;
        initComponents();
    }

    public void setContenido(JPanel panel) {
        panel.setVisible(true);
        jpnlContenedor.removeAll();
        jpnlContenedor.add(panel);
        jpnlContenedor.revalidate();
        jpnlContenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jPanelAzul = new javax.swing.JPanel();
        textPotroEventos = new javax.swing.JLabel();
        jPanelAzulOscuro = new javax.swing.JPanel();
        busqueda = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        botonInicio1 = new javax.swing.JButton();
        jpnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanelBase.setBackground(new java.awt.Color(255, 255, 255));

        jPanelAzul.setBackground(new java.awt.Color(31, 92, 204));
        jPanelAzul.setPreferredSize(new java.awt.Dimension(597, 50));

        textPotroEventos.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        textPotroEventos.setForeground(new java.awt.Color(255, 255, 255));
        textPotroEventos.setText("PotroEventos");

        jPanelAzulOscuro.setBackground(new java.awt.Color(0, 49, 141));

        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(0, 49, 141));
        btnConsultar.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        botonInicio1.setBackground(new java.awt.Color(0, 49, 141));
        botonInicio1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        botonInicio1.setForeground(new java.awt.Color(255, 255, 255));
        botonInicio1.setText("Inicio");
        botonInicio1.setBorder(null);
        botonInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicio1MouseClicked(evt);
            }
        });
        botonInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAzulOscuroLayout = new javax.swing.GroupLayout(jPanelAzulOscuro);
        jPanelAzulOscuro.setLayout(jPanelAzulOscuroLayout);
        jPanelAzulOscuroLayout.setHorizontalGroup(
            jPanelAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulOscuroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonInicio1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAzulOscuroLayout.setVerticalGroup(
            jPanelAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulOscuroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(btnConsultar)
                    .addComponent(botonInicio1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelAzulLayout = new javax.swing.GroupLayout(jPanelAzul);
        jPanelAzul.setLayout(jPanelAzulLayout);
        jPanelAzulLayout.setHorizontalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textPotroEventos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelAzulOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAzulLayout.setVerticalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPotroEventos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAzulOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jpnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jpnlContenedor.setPreferredSize(new java.awt.Dimension(824, 350));
        jpnlContenedor.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE)
            .addComponent(jpnlContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE)
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addComponent(jPanelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void botonInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInicio1ActionPerformed

    private void botonInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicio1MouseClicked
        //coordinador.volverACategorias();
    }//GEN-LAST:event_botonInicio1MouseClicked

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        coordinador.mostrarConsultar();
    }//GEN-LAST:event_btnConsultarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicio1;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JTextField busqueda;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPanel jPanelAzulOscuro;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jpnlContenedor;
    private javax.swing.JLabel textPotroEventos;
    // End of variables declaration//GEN-END:variables
}
