/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Controlador.interfaz.ICoordinadorAplicacion;
import Pantallas.vistas.PnlCategoria;
import Pantallas.vistas.PnlEventos;
import dtos.CategoriaDTO;
import dtos.UsuarioDTO;
import excepciones.GestionEventoException;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Aaron Burciaga - 262788
 * @author Brian Sandoval - 262741
 * @author Dayanara Peralta - 262695
 * @author María Valdez - 262775
 */
public class FrmPlantillaSistema extends javax.swing.JFrame {

    private ICoordinadorAplicacion coordinador;

    /**
     * Creates new form FrmPlantillaSistema
     */
    public FrmPlantillaSistema(ICoordinadorAplicacion coordinador) {
        this.coordinador = coordinador;
        initComponents();
        setLocationRelativeTo(null);
        jpnlContenedor.setLayout(new GridLayout(0, 3, 10, 10));
        txtCreditos.setText(coordinador.getUsuarioSesion().getCreditos().toString());
    }
    
    public void setCreditos(String creditos){
        txtCreditos.setText(creditos);
    }

    public void setContenido(JPanel panel) {
        jpnlContenedor.removeAll();

        jpnlContenedor.setLayout(new java.awt.BorderLayout());

        jpnlContenedor.add(panel, java.awt.BorderLayout.CENTER);

        jpnlContenedor.revalidate();
        jpnlContenedor.repaint();
    }

    public void setCategorias() {
        jpnlContenedor.removeAll();

        jpnlContenedor.setLayout(new GridLayout(0, 3, 10, 10));

        List<CategoriaDTO> categorias = coordinador.consultarCategorias();
        for (CategoriaDTO categoria : categorias) {
            jpnlContenedor.add(new PnlCategoria(categoria, this, coordinador));
        }

        jpnlContenedor.revalidate();
        jpnlContenedor.repaint();
    }

    public void setEventos(CategoriaDTO categoria) throws GestionEventoException {
        jpnlContenedor.removeAll();
        jpnlContenedor.add(new PnlEventos(coordinador, categoria));

        jpnlContenedor.revalidate();
        jpnlContenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jPanelAzul = new javax.swing.JPanel();
        textPotroEventos = new javax.swing.JLabel();
        jPanelAzulOscuro = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        botonInicio1 = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        iconCredito = new javax.swing.JLabel();
        lblCreditosN = new javax.swing.JLabel();
        txtCreditos = new javax.swing.JLabel();
        jpnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanelBase.setBackground(new java.awt.Color(255, 255, 255));

        jPanelAzul.setBackground(new java.awt.Color(31, 92, 204));
        jPanelAzul.setPreferredSize(new java.awt.Dimension(597, 50));

        textPotroEventos.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        textPotroEventos.setForeground(new java.awt.Color(255, 255, 255));
        textPotroEventos.setText("PotroEventos");

        jPanelAzulOscuro.setBackground(new java.awt.Color(0, 49, 141));

        btnConsultar.setBackground(new java.awt.Color(0, 49, 141));
        btnConsultar.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setFocusPainted(false);
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        botonInicio1.setBackground(new java.awt.Color(0, 49, 141));
        botonInicio1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        botonInicio1.setForeground(new java.awt.Color(255, 255, 255));
        botonInicio1.setText("Inicio");
        botonInicio1.setBorder(null);
        botonInicio1.setFocusPainted(false);
        botonInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicio1MouseClicked(evt);
            }
        });
        botonInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicio1ActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(0, 49, 141));
        btnCerrarSesion.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        iconCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/creditos.png"))); // NOI18N

        lblCreditosN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreditosN.setForeground(new java.awt.Color(255, 255, 255));
        lblCreditosN.setText("Créditos:");

        txtCreditos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCreditos.setForeground(new java.awt.Color(255, 255, 255));
        txtCreditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCreditos.setText("-");

        javax.swing.GroupLayout jPanelAzulOscuroLayout = new javax.swing.GroupLayout(jPanelAzulOscuro);
        jPanelAzulOscuro.setLayout(jPanelAzulOscuroLayout);
        jPanelAzulOscuroLayout.setHorizontalGroup(
            jPanelAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulOscuroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonInicio1)
                .addGap(54, 54, 54)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCreditosN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnCerrarSesion)
                .addGap(18, 18, 18))
        );
        jPanelAzulOscuroLayout.setVerticalGroup(
            jPanelAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulOscuroLayout.createSequentialGroup()
                .addGroup(jPanelAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConsultar)
                        .addComponent(botonInicio1)
                        .addComponent(btnCerrarSesion)
                        .addComponent(lblCreditosN, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCreditos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAzulLayout = new javax.swing.GroupLayout(jPanelAzul);
        jPanelAzul.setLayout(jPanelAzulLayout);
        jPanelAzulLayout.setHorizontalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textPotroEventos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelAzulOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAzulLayout.setVerticalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPotroEventos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAzulOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jpnlContenedor.setPreferredSize(new java.awt.Dimension(824, 350));
        jpnlContenedor.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE)
            .addComponent(jpnlContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE)
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addComponent(jPanelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void botonInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInicio1ActionPerformed

    private void botonInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicio1MouseClicked
        coordinador.mostrarInicio();
    }//GEN-LAST:event_botonInicio1MouseClicked

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        coordinador.mostrarConsultar();
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
                this, "¿Estás seguro de que deseas cerrar sesión?",
                "Confirmar salida", javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            coordinador.cerrarSesion();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicio1;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel iconCredito;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPanel jPanelAzulOscuro;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jpnlContenedor;
    private javax.swing.JLabel lblCreditosN;
    private javax.swing.JLabel textPotroEventos;
    private javax.swing.JLabel txtCreditos;
    // End of variables declaration//GEN-END:variables
}
