/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Controlador.interfaz.ICoordinadorAplicacion;
import utilerias.BotonUtileria;

/**
 *
 * @author Aaron Burciaga - 262788
 * @author Brian Sandoval - 262741
 * @author Dayanara Peralta - 262695
 * @author María Valdez - 262775
 */
public class FrmRegistrarse extends javax.swing.JFrame {

    private ICoordinadorAplicacion coordinador;

    public FrmRegistrarse() {
        initComponents();

    }

    /**
     * Creates new form frmInicioSesion
     *
     * @param coordinador
     */
    public FrmRegistrarse(ICoordinadorAplicacion coordinador) {
        this.coordinador = coordinador;
        initComponents();
        BotonUtileria.estilizarBoton(btnRegistrarse);
        BotonUtileria.estilizarBoton(iniciaSesion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iniciaSesion = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        textContrasenia = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        textCorreo = new javax.swing.JLabel();
        jPanelAzul = new javax.swing.JPanel();
        textiniciaSesion = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtConfirmacionContrasenia = new javax.swing.JPasswordField();
        textContrasenia1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(845, 465));

        iniciaSesion.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        iniciaSesion.setForeground(new java.awt.Color(0, 0, 0));
        iniciaSesion.setText("<html>¿Ya tienes cuenta? <font color=\"blue\"><u>Iniciar Sesión</u></font></html>");
        iniciaSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciaSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciaSesionMouseClicked(evt);
            }
        });

        txtContrasenia.setBackground(new java.awt.Color(234, 230, 230));

        textContrasenia.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        textContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        textContrasenia.setText("Contraseña");

        txtCorreo.setBackground(new java.awt.Color(234, 230, 230));
        txtCorreo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(217, 217, 217));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        textCorreo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        textCorreo.setForeground(new java.awt.Color(0, 0, 0));
        textCorreo.setText("Correo");

        jPanelAzul.setBackground(new java.awt.Color(31, 92, 204));
        jPanelAzul.setPreferredSize(new java.awt.Dimension(597, 50));

        textiniciaSesion.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        textiniciaSesion.setForeground(new java.awt.Color(255, 255, 255));
        textiniciaSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textiniciaSesion.setText("Registrarse");

        javax.swing.GroupLayout jPanelAzulLayout = new javax.swing.GroupLayout(jPanelAzul);
        jPanelAzul.setLayout(jPanelAzulLayout);
        jPanelAzulLayout.setHorizontalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textiniciaSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAzulLayout.setVerticalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textiniciaSesion)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnRegistrarse.setBackground(new java.awt.Color(44, 114, 243));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrarse");

        javax.swing.GroupLayout btnRegistrarseLayout = new javax.swing.GroupLayout(btnRegistrarse);
        btnRegistrarse.setLayout(btnRegistrarseLayout);
        btnRegistrarseLayout.setHorizontalGroup(
            btnRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );
        btnRegistrarseLayout.setVerticalGroup(
            btnRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        txtConfirmacionContrasenia.setBackground(new java.awt.Color(234, 230, 230));

        textContrasenia1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        textContrasenia1.setForeground(new java.awt.Color(0, 0, 0));
        textContrasenia1.setText("Confirmar contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(iniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textContrasenia1)
                            .addComponent(textContrasenia)
                            .addComponent(textCorreo)
                            .addComponent(txtContrasenia)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(txtConfirmacionContrasenia))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(textCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(textContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(textContrasenia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmacionContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(iniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciaSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciaSesionMouseClicked
        coordinador.mostrarInicioSesion();
    }//GEN-LAST:event_iniciaSesionMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnRegistrarse;
    private javax.swing.JLabel iniciaSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JLabel textContrasenia;
    private javax.swing.JLabel textContrasenia1;
    private javax.swing.JLabel textCorreo;
    private javax.swing.JLabel textiniciaSesion;
    private javax.swing.JPasswordField txtConfirmacionContrasenia;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
