/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.vistas;

import java.awt.Image;
import java.awt.Panel;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author maria
 */
public class PnlCategoria extends javax.swing.JPanel {
    
    private CategoriaDTO categoria;
    private Panel padre;

    /**
     * Creates new form PnlCategoria
     */
    public PnlCategoria(CategoriaDTO categoria, Panel padre) {
        this.categoria = categoria;
        this.padre = padre;
        initComponents();
        setImagen();
    }
    
    public void setImagen() {
        if (categoria == null) {
            return;
        }
        ImageIcon icono = new ImageIcon(categoria.getUrlImagen());
        int ancho = getWidth();
        int alto = getHeight();
        if (ancho <= 0) {
            ancho = 250;
        }
        if (alto <= 0) {
            alto = 187;
        }
        Image img = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        iconCategoria.setIcon(new ImageIcon(img));
        iconCategoria.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconCategoria = new javax.swing.JLabel();

        iconCategoria.setText("iconCategoria");
        iconCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconCategoriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iconCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconCategoriaMouseClicked
        // TODO add your handling code here:
        padre.abrirEventosCategoria(categoria);
    }//GEN-LAST:event_iconCategoriaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconCategoria;
    // End of variables declaration//GEN-END:variables
}
