/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.vistas;

import Controlador.interfaz.ICoordinadorAplicacion;
import dtos.CategoriaDTO;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author maria
 */
public class PnlCategoria extends javax.swing.JPanel {

    private CategoriaDTO categoria;
    private ICoordinadorAplicacion coordinador;

    public PnlCategoria(CategoriaDTO categoria, Component padre, ICoordinadorAplicacion coordinador) {
        this.categoria = categoria;
        this.coordinador = coordinador;

        initComponents();

        // CONFIGURACIÓN DE LAYOUT PARA QUITAR ESPACIOS
        this.setLayout(new java.awt.BorderLayout(0, 0)); // 0 espacio horizontal y vertical

        // Ajustamos el label del nombre
        lblNombreCategoria.setOpaque(true);
        lblNombreCategoria.setBackground(new java.awt.Color(240, 240, 240)); // Un gris claro para el nombre
        lblNombreCategoria.setPreferredSize(new java.awt.Dimension(250, 30));

        // Añadimos al panel
        this.add(lblNombreCategoria, java.awt.BorderLayout.NORTH);
        this.add(iconCategoria, java.awt.BorderLayout.CENTER);

        setNombre();
        setImagen();
    }

    public void setNombre() {
        if (categoria != null && categoria.getNombreCategoria() != null) {
            lblNombreCategoria.setText(categoria.getNombreCategoria().name());
        }
    }

    public void setImagen() {
        if (categoria == null || categoria.getUrlImagen() == null) {
            return;
        }

            String rutaLimpia = categoria.getUrlImagen().replace("/src/main/resources", "");
            String rutaAlternativa = categoria.getUrlImagen().replace("src/main/resources", "");

            java.net.URL imgUrl = getClass().getResource(rutaLimpia);
            if (imgUrl == null) {
                imgUrl = getClass().getResource(rutaAlternativa);
            }

            if (imgUrl != null) {
                ImageIcon icono = new ImageIcon(imgUrl);

                int ancho = 306;
                int alto = 202;

                Image imagenEscalada = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                iconCategoria.setIcon(new ImageIcon(imagenEscalada));
            }
            iconCategoria.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconCategoria = new javax.swing.JLabel();
        lblNombreCategoria = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        iconCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconCategoriaMouseClicked(evt);
            }
        });

        lblNombreCategoria.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblNombreCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCategoria.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblNombreCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(iconCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iconCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconCategoriaMouseClicked
        // TODO add your handling code here:
        coordinador.mostrarEventos(categoria);
    }//GEN-LAST:event_iconCategoriaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconCategoria;
    private javax.swing.JLabel lblNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
