/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.vistas;

import Controlador.coordinador.CoordinadorAplicacion;
import Controlador.interfaz.ICoordinadorAplicacion;
import dtos.CategoriaDTO;
import java.awt.Component;
import java.awt.Image;
import java.awt.Panel;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author maria
 */
public class PnlCategoria extends javax.swing.JPanel {

    private CategoriaDTO categoria;
    private Component padre;
    private ICoordinadorAplicacion coordinador;

    /**
     * Creates new form PnlCategoria
     */
    public PnlCategoria(CategoriaDTO categoria, Component padre, ICoordinadorAplicacion coordinador) {
        this.categoria = categoria;
        this.padre = padre;
        this.coordinador = coordinador;
        initComponents();
        setImagen();

    }

    public void setImagen() {
        if (categoria == null) {
            return;
        }

        java.net.URL url = getClass().getResource(categoria.getUrlImagen());
        if (url == null) {
            return;
        }

        ImageIcon icono = new ImageIcon(url);

        int lblW = iconCategoria.getWidth();
        int lblH = iconCategoria.getHeight();

        if (lblW == 0 || lblH == 0) {
            lblW = 250;
            lblH = 187;
        }

        int imgW = icono.getIconWidth();
        int imgH = icono.getIconHeight();

        double escala = Math.min((double) lblW / imgW, (double) lblH / imgH);

        int newW = (int) (imgW * escala);
        int newH = (int) (imgH * escala);

        Image img = icono.getImage().getScaledInstance(newW, newH, Image.SCALE_SMOOTH);

        iconCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCategoria.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

        iconCategoria.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconCategoria = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        iconCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconCategoriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iconCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconCategoriaMouseClicked
        // TODO add your handling code here:
        coordinador.mostrarEventos(categoria);
    }//GEN-LAST:event_iconCategoriaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconCategoria;
    // End of variables declaration//GEN-END:variables
}
