/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.vistas;

import Controlador.interfaz.ICoordinadorAplicacion;
import dtos.ENUMS.ReservacionEstadoDTO;
import dtos.ReservacionDTO;
import dtos.UsuarioDTO;
import java.awt.Dimension;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;

/**
 *
 * @author Aaron Burciaga - 262788
 * @author Brian Sandoval - 262741
 * @author Dayanara Peralta - 262695
 * @author María Valdez - 262775
 */
public class PnlConsultar extends javax.swing.JPanel {

    private ICoordinadorAplicacion coordinador;

    private UsuarioDTO usuario;

    /**
     * Creates new form PnlConsultar
     */
    public PnlConsultar(ICoordinadorAplicacion coordinador) {
        this.coordinador = coordinador;
        this.usuario = coordinador.getUsuarioSesion();
        initComponents();
        cargarInfo();
    }

    public void mostrarDetalles(ReservacionDTO reservacion) {
        coordinador.mostrarDetalles(reservacion);
    }
    
    private void cargarInfo(){
        List<ReservacionDTO> proximos = new ArrayList<>();
        List<ReservacionDTO> pasados = new ArrayList<>();
        List<ReservacionDTO> cancelados = new ArrayList<>();
        for (ReservacionDTO r : coordinador.consultarReservaciones(usuario.getIdUsuario())) {
            if (r.getEstado() == ReservacionEstadoDTO.CANCELADA) {
                cancelados.add(r);
            } else if (r.getEstado() == ReservacionEstadoDTO.ACTIVA && r.getBoleto().getEvento().getFechaHora().isAfter(LocalDateTime.now())) {
                proximos.add(r);
            } else {
                pasados.add(r);
            }
        }
        pnlProximos.setLayout(new BoxLayout(pnlProximos, BoxLayout.Y_AXIS));
        pnlPasados.setLayout(new BoxLayout(pnlPasados, BoxLayout.Y_AXIS));
        pnlCancelados.setLayout(new BoxLayout(pnlCancelados, BoxLayout.Y_AXIS));
        for (ReservacionDTO proximo : proximos) {
            PnlEvento panel = PnlEvento.crearParaConsulta(proximo, this, coordinador);
            panel.setMaximumSize(new Dimension(Integer.MAX_VALUE, panel.getPreferredSize().height));
            pnlProximos.add(panel);
            JSeparator separador = new JSeparator(SwingConstants.HORIZONTAL);
            separador.setMaximumSize(new Dimension(Integer.MAX_VALUE, 10)); // 10px de alto para el separador
            pnlProximos.add(separador);
        }
        pnlProximos.add(Box.createVerticalGlue());
        pnlProximos.revalidate();
        pnlProximos.repaint();
        for (ReservacionDTO pasado : pasados) {
            PnlEvento panel = PnlEvento.crearParaConsulta(pasado, this, coordinador);
            panel.setMaximumSize(new Dimension(Integer.MAX_VALUE, panel.getPreferredSize().height));
            pnlPasados.add(panel);
            JSeparator separador = new JSeparator(SwingConstants.HORIZONTAL);
            separador.setMaximumSize(new Dimension(Integer.MAX_VALUE, 10));
            pnlPasados.add(separador);
        }
        pnlPasados.add(Box.createVerticalGlue());
        pnlPasados.revalidate();
        pnlPasados.repaint();
        for (ReservacionDTO cancelado : cancelados) {
            PnlEvento panel = PnlEvento.crearParaConsulta(cancelado, this, coordinador);
            panel.setMaximumSize(new Dimension(Integer.MAX_VALUE, panel.getPreferredSize().height));
            pnlCancelados.add(panel);
            JSeparator separador = new JSeparator(SwingConstants.HORIZONTAL);
            separador.setMaximumSize(new Dimension(Integer.MAX_VALUE, 10));
            pnlCancelados.add(separador);
        }
        pnlCancelados.add(Box.createVerticalGlue());
        pnlCancelados.revalidate();
        pnlCancelados.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlProximos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlPasados = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnlCancelados = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jEditorPane1);

        setOpaque(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Eventos Próximos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Eventos Pasados");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Eventos Cancelados");

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlProximos.setLayout(new javax.swing.BoxLayout(pnlProximos, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(pnlProximos);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlPasados.setLayout(new javax.swing.BoxLayout(pnlPasados, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane3.setViewportView(pnlPasados);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlCancelados.setLayout(new javax.swing.BoxLayout(pnlCancelados, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane4.setViewportView(pnlCancelados);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlCancelados;
    private javax.swing.JPanel pnlPasados;
    private javax.swing.JPanel pnlProximos;
    // End of variables declaration//GEN-END:variables
}
