/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.vistas;

import java.awt.Image;
import java.awt.Panel;
import javax.swing.ImageIcon;

/**
 *
 * @author Aaron Burciaga - 262788
 * @author Brian Sandoval - 262741
 * @author Dayanara Peralta - 262695
 * @author María Valdez - 262775
 */
public class PnlEvento extends javax.swing.JPanel {
    
    private boolean modoConsulta;
    private boolean modoVista;
    private EventoDTO evento;
    private ReservacionDTO reservacion;
    private Panel padre;
    
    /**
     * Constructor PRIVADO. Solo puede ser llamado por los métodos estáticos de abajo.
     */
    private PnlEvento(EventoDTO evento, ReservacionDTO reservacion, Panel padre, boolean modoConsulta) {
        this.evento = evento;
        this.reservacion = reservacion;
        this.padre = padre;
        this.modoConsulta = modoConsulta;
        this.modoVista = !modoConsulta;
        
        initComponents();
        cargarEvento();
        configurarModo();
    }

    public static PnlEvento crearParaVista(EventoDTO evento, Panel padre) {
        // Le pasamos null a la reservación y false al modoConsulta
        return new PnlEvento(evento, null, padre, false); 
    }

    public static PnlEvento crearParaConsulta(EventoDTO evento, ReservacionDTO reservacion, Panel padre) {
        // Le pasamos la reservación y true al modoConsulta
        return new PnlEvento(evento, reservacion, padre, true);
    }

    private void cargarEvento(){
        ImageIcon icono = new ImageIcon(evento.getUrlImagen());
        int ancho = getWidth();
        int alto = getHeight();
        if (ancho <= 0) {
            ancho = 270;
        }
        if (alto <= 0) {
            alto = 188;
        }
        Image img = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        iconEvento.setIcon(new ImageIcon(img));
        iconEvento.setText("");
        this.lblNombre.setText(evento.getNombre());
        this.lblFechaHora.setText(evento.getFecha());
        this.lblUbicacion.setText(evento.getUbicacion());
    }

    private void configurarModo() {
        if (modoConsulta) {
            btnMostrar.setText("Ver mis boletos");
        } else {
            btnMostrar.setText("Mostrar Información");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        iconEvento = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(221, 212, 212));
        setMaximumSize(new java.awt.Dimension(270, 188));
        setMinimumSize(new java.awt.Dimension(270, 188));
        setPreferredSize(new java.awt.Dimension(270, 188));

        lblNombre.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        lblFechaHora.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblFechaHora.setText("Fecha y Hora");

        lblUbicacion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblUbicacion.setText("Ubicación");

        iconEvento.setText("iconEvento");

        btnMostrar.setBackground(new java.awt.Color(31, 92, 204));
        btnMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("Mostrar Información");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaHora)
                        .addGap(18, 18, 18)
                        .addComponent(lblUbicacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        if(modoConsulta){
            padre.mostrarDetalles(evento);
        } else {
            padre.mostrarEvento(evento);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel iconEvento;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUbicacion;
    // End of variables declaration//GEN-END:variables
}
